// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA76Me94uJJk2yPurBigi5_GCP425wAef4',
    appId: '1:397419120027:web:8a3727a14dc9f55b2f8d3e',
    messagingSenderId: '397419120027',
    projectId: 'flutterfirebaseauthentic-84b6e',
    authDomain: 'flutterfirebaseauthentic-84b6e.firebaseapp.com',
    storageBucket: 'flutterfirebaseauthentic-84b6e.firebasestorage.app',
    measurementId: 'G-4SC18N8HNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDI5dvfYQXn1_pxMMP0gOOHaVA78VFEms',
    appId: '1:397419120027:android:950038cb1c8c950a2f8d3e',
    messagingSenderId: '397419120027',
    projectId: 'flutterfirebaseauthentic-84b6e',
    storageBucket: 'flutterfirebaseauthentic-84b6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQktp01aes_yZucJfea5-F0WoTL5Y-Z6Y',
    appId: '1:397419120027:ios:3c44fcf46a086d402f8d3e',
    messagingSenderId: '397419120027',
    projectId: 'flutterfirebaseauthentic-84b6e',
    storageBucket: 'flutterfirebaseauthentic-84b6e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQktp01aes_yZucJfea5-F0WoTL5Y-Z6Y',
    appId: '1:397419120027:ios:3c44fcf46a086d402f8d3e',
    messagingSenderId: '397419120027',
    projectId: 'flutterfirebaseauthentic-84b6e',
    storageBucket: 'flutterfirebaseauthentic-84b6e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA76Me94uJJk2yPurBigi5_GCP425wAef4',
    appId: '1:397419120027:web:35c7efb7337222b52f8d3e',
    messagingSenderId: '397419120027',
    projectId: 'flutterfirebaseauthentic-84b6e',
    authDomain: 'flutterfirebaseauthentic-84b6e.firebaseapp.com',
    storageBucket: 'flutterfirebaseauthentic-84b6e.firebasestorage.app',
    measurementId: 'G-T4M1DZHGJM',
  );
}
