class StringConstants {
  static String logIn = 'Log In';
  static String register = 'Register';
  static String forgotPassword = 'Forgot Password';
  static String firebaseAuthentication = 'Firebase Authentication';
  static String logInWithGoogle = 'Log in with Google';
  static String logInWithApple = 'Log in with Apple';
  static String logInToYourAccount = 'Log in to your account ✨';
  static String welcomeBack = 'Welcome back! Please enter your details.';
  static String email = 'Email';
  static String password = 'Password';
  static String doNotHaveAnAccount = "Don't have an account?";
  static String signUp = 'Sign Up';
  static String enterYourEmail = 'Enter your email';
  static String createYourAccount = 'Create your Account ✨';
  static String confirmPassword = 'Confirm Password';
  static String alreadyHaveAnAccount = 'Allready have an account?';
  static String welcome = 'Welcome! Please enter your details.';
  static String enterYourPassword = 'Enter your password';
  static String passwordDoNotMatch = "Passwords Don't Match";
  static String registrationSuccesful = 'Registration Succesful!';
  static String anErrorOccured = 'An error occured';
  static String userNotFount = 'User not found';
  static String noUserFoundForThatEmail = 'No user found for that email';
  static String wrongPassword = 'Wrong Password';
  static String wrongPasswordProvided = 'Wrong password provided';
  static String congratulations = 'Congratulations';
  static String loginSuccesful = 'Login succesful';
}
